#!/usr/bin/env python3
"""Interop gate: drive the TASE.2 server with an independent MMS client stack.

This is the credibility test. It uses pyiec61850 (the SWIG binding to libIEC61850,
a different code path from this project's own C client and agent) to prove a
third-party stack can associate with the server, decode its object model, and run
the core ICCP services:

  * Block 1: association + reads of the VMD and ICC objects and of indication
    points (value + quality + time tag)
  * Block 2: define a data set, bind and enable a DS transfer set
  * Block 5: device control, including select-before-operate and its enforcement

It is skipped automatically if the server binary or pyiec61850 are not built, so
the rest of the suite still runs. Build them with ./scripts/10_build.sh.

Report reception over pyiec61850 is not asserted here: its Python callback for
unsolicited InformationReports is not generated by the binding (a SWIG director
limitation, not a server issue). The Block 2 report path is covered by the C
agent in the shell smoke tests and the capture proofs in docs/.
"""
import os
import subprocess
import sys
import time
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
SERVER = os.path.join(ROOT, "src", "tase2_server")
PYBIND = os.path.join(ROOT, "deps", "libiec61850", "build", "pyiec61850")
CONFIG = os.path.join(ROOT, "config", "scada.json")
GEN = os.path.join(ROOT, "scripts", "gen_server_points.py")
PORT = 11502
DOMAIN = "TestDomain"

_have = os.path.isfile(SERVER) and os.path.isfile(os.path.join(PYBIND, "pyiec61850.py"))
if _have:
    sys.path.insert(0, PYBIND)
    try:
        import pyiec61850 as mms
    except Exception:
        _have = False


@unittest.skipUnless(_have, "server binary or pyiec61850 not built (run scripts/10_build.sh)")
class TestInterop(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        pts = subprocess.check_output([sys.executable, GEN, CONFIG])
        cls.points = os.path.join(HERE, ".interop_points.conf")
        with open(cls.points, "wb") as f:
            f.write(pts)
        cls.srv = subprocess.Popen(
            [SERVER, "-i", "127.0.0.1", "-p", str(PORT), "-d", DOMAIN,
             "-o", "60", "-n", "-P", cls.points],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        # wait until it accepts an association
        deadline = time.time() + 10
        while time.time() < deadline:
            c = mms.MmsConnection_create()
            if mms.MmsConnection_connect(c, mms.toMmsErrorP(), "127.0.0.1", PORT):
                mms.MmsConnection_destroy(c)
                break
            mms.MmsConnection_destroy(c)
            time.sleep(0.3)

    @classmethod
    def tearDownClass(cls):
        cls.srv.terminate()
        try:
            cls.srv.wait(timeout=3)
        except subprocess.TimeoutExpired:
            cls.srv.kill()
        if os.path.isfile(cls.points):
            os.remove(cls.points)

    def _connect(self):
        con = mms.MmsConnection_create()
        self.assertTrue(mms.MmsConnection_connect(con, mms.toMmsErrorP(), "127.0.0.1", PORT),
                        "third-party client could not associate")
        return con

    def test_block1_association_and_reads(self):
        con = self._connect()
        err = mms.toMmsErrorP()
        try:
            ver = mms.MmsConnection_readVariable(con, err, None, "TASE2_Version")
            self.assertIsNotNone(ver, "TASE2_Version not readable at VMD scope")
            self.assertEqual(mms.MmsValue_toInt32(mms.MmsValue_getElement(ver, 0)), 2000)

            for vmd in ("Supported_Features",):
                self.assertIsNotNone(mms.MmsConnection_readVariable(con, err, None, vmd))
            for icc in ("Bilateral_Table_ID", "Next_DSTransfer_Set"):
                self.assertIsNotNone(mms.MmsConnection_readVariable(con, err, DOMAIN, icc),
                                     "%s not readable in ICC domain" % icc)

            # an indication point decodes as { Value, Flags, TimeStamp }
            pt = mms.MmsConnection_readVariable(con, err, DOMAIN, "plc1_mw")
            self.assertIsNotNone(pt)
            self.assertEqual(mms.MmsValue_getTypeString(pt), "structure")
            self.assertGreaterEqual(mms.MmsValue_getArraySize(pt), 3,
                                    "point should carry Value, Flags and TimeStamp")
        finally:
            mms.MmsConnection_destroy(con)

    def test_block2_transfer_set_config(self):
        con = self._connect()
        err = mms.toMmsErrorP()
        try:
            ll = mms.LinkedList_create()
            for it in ("plc1_mw", "plc1_kv", "plc1_brk"):
                mms.LinkedList_add(ll, mms.MmsVariableAccessSpecification_create(DOMAIN, it))
            mms.MmsConnection_deleteNamedVariableList(con, err, DOMAIN, "ds_interop")
            mms.MmsConnection_defineNamedVariableList(con, err, DOMAIN, "ds_interop", ll)
            mms.MmsConnection_writeVariable(con, err, DOMAIN, "DSTransferSet01$DataSetName",
                                            mms.MmsValue_newVisibleString("ds_interop"))
            mms.MmsConnection_writeVariable(con, err, DOMAIN, "DSTransferSet01$Status",
                                            mms.MmsValue_newIntegerFromInt32(1))
            # the binding accepted; confirm the server stored the binding
            ds = mms.MmsConnection_readVariable(con, err, DOMAIN, "DSTransferSet01$DataSetName")
            self.assertEqual(mms.MmsValue_toString(ds), "ds_interop")
        finally:
            mms.MmsConnection_destroy(con)

    def test_block5_sbo_enforced(self):
        con = self._connect()
        err = mms.toMmsErrorP()
        try:
            def cmd():
                v = mms.MmsConnection_readVariable(con, err, DOMAIN, "plc1_brk_ctl")
                return mms.MmsValue_toInt32(mms.MmsValue_getElement(v, 0))

            self.assertEqual(cmd(), 0, "control should start cleared")

            # operate without selecting first -> rejected, command unchanged
            mms.MmsConnection_writeVariable(con, err, DOMAIN, "plc1_brk_ctl$Command",
                                            mms.MmsValue_newIntegerFromInt32(1))
            self.assertEqual(cmd(), 0, "SBO operate without select must be rejected")

            # select then operate -> accepted
            mms.MmsConnection_writeVariable(con, err, DOMAIN, "plc1_brk_ctl$SBO",
                                            mms.MmsValue_newIntegerFromInt32(1))
            mms.MmsConnection_writeVariable(con, err, DOMAIN, "plc1_brk_ctl$Command",
                                            mms.MmsValue_newIntegerFromInt32(1))
            self.assertEqual(cmd(), 1, "SBO operate after select must be accepted")
        finally:
            mms.MmsConnection_destroy(con)


if __name__ == "__main__":
    unittest.main(verbosity=2)
